# Generated by Django 3.1.7 on 2021-08-08 09:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0004_review_createdat'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('message', models.CharField(blank=True, max_length=200, null=True)),
                ('_id', models.AutoField(editable=False, primary_key=True, serialize=False)),
            ],
        ),
    ]
