# Generated by Django 3.1.7 on 2021-08-12 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shopify', '0005_message'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='category',
            field=models.CharField(blank=True, choices=[('laptop', 'Laptop'), ('phones', 'Cell Phones'), ('cloths', 'Cloths'), ('fridge', 'Fridge'), ('watch', 'Watch'), ('shoes', 'Shoes')], default='cloths', max_length=200, null=True),
        ),
    ]
